import dbConnect from '@/lib/dbConnect';
import Player from '@/models/Player';
import { NextApiRequest, NextApiResponse } from 'next';

// Replace with your own list
const obscurePlayers = [
    {
        name: 'CJ McCollum',
        college: 'Lehigh',
        position: 'SG',
        conference: 'Patriot League',
        mascot: 'Mountain Hawks',
        colors: ['Brown', 'White'],
        region: 'Northeast',
        collegeInitial: 'LU',
    },
    {
        name: 'Jimmy Butler',
        college: 'Marquette',
        position: 'SF',
        conference: 'Big East',
        mascot: 'Golden Eagles',
        colors: ['Blue', 'Gold'],
        region: 'Midwest',
        collegeInitial: 'MU',
    },
    {
        name: 'Ja Morant',
        college: 'Murray State',
        position: 'PG',
        conference: 'Missouri Valley',
        mascot: 'Racers',
        colors: ['Navy', 'Gold'],
        region: 'South',
        collegeInitial: 'MUR',
    },
    {
        name: 'Kenneth Faried',
        college: 'Morehead State',
        position: 'PF',
        conference: 'Ohio Valley',
        mascot: 'Eagles',
        colors: ['Blue', 'Gold'],
        region: 'South',
        collegeInitial: 'MSU',
    },
    {
        name: 'Stephen Curry',
        college: 'Davidson',
        position: 'PG',
        conference: 'Atlantic 10',
        mascot: 'Wildcats',
        colors: ['Red', 'Black'],
        region: 'South',
        collegeInitial: 'DC',
    },
    {
        name: 'Jimmer Fredette',
        college: 'BYU',
        position: 'SG',
        conference: 'Big 12',
        mascot: 'Cougars',
        colors: ['Navy Blue', 'White'],
        region: 'West',
        collegeInitial: 'BYU',
    },
    {
        name: 'Kawhi Leonard',
        college: 'San Diego State',
        position: 'SF',
        conference: 'Mountain West',
        mascot: 'Aztecs',
        colors: ['Black', 'Scarlet'],
        region: 'West',
        collegeInitial: 'SDSU',
    },
    {
        name: 'Damian Lillard',
        college: 'Weber State',
        position: 'PG',
        conference: 'Big Sky',
        mascot: 'Wildcats',
        colors: ['Purple', 'White'],
        region: 'West',
        collegeInitial: 'WSU',
    },
    {
        name: 'Ronnie Brewer',
        college: 'Arkansas',
        position: 'SG',
        conference: 'SEC',
        mascot: 'Razorbacks',
        colors: ['Cardinal', 'White'],
        region: 'South',
        collegeInitial: 'UA',
    },
    {
        name: 'Norris Cole',
        college: 'Cleveland State',
        position: 'PG',
        conference: 'Horizon League',
        mascot: 'Vikings',
        colors: ['Green', 'White'],
        region: 'Midwest',
        collegeInitial: 'CSU',
    },
    {
        name: 'Devin Brown',
        college: 'UTSA',
        position: 'SG',
        conference: 'Southland',
        mascot: 'Roadrunners',
        colors: ['Blue', 'Orange'],
        region: 'South',
        collegeInitial: 'UTSA',
    },
    {
        name: 'Courtney Lee',
        college: 'Western Kentucky',
        position: 'SG',
        conference: 'Sun Belt',
        mascot: 'Hilltoppers',
        colors: ['Red', 'White'],
        region: 'South',
        collegeInitial: 'WKU',
    },
    {
        name: 'George Hill',
        college: 'IUPUI',
        position: 'PG',
        conference: 'Horizon League',
        mascot: 'Jaguars',
        colors: ['Crimson', 'Gold'],
        region: 'Midwest',
        collegeInitial: 'IUPUI',
      },
      {
        name: 'Delon Wright',
        college: 'Utah',
        position: 'PG',
        conference: 'Pac-12',
        mascot: 'Utes',
        colors: ['Red', 'White'],
        region: 'West',
        collegeInitial: 'UU',
      },
      {
        name: 'Robert Covington',
        college: 'Tennessee State',
        position: 'SF',
        conference: 'OVC',
        mascot: 'Tigers',
        colors: ['Blue', 'White'],
        region: 'South',
        collegeInitial: 'TSU',
      },
      {
        name: 'Troy Daniels',
        college: 'VCU',
        position: 'SG',
        conference: 'Atlantic 10',
        mascot: 'Rams',
        colors: ['Black', 'Gold'],
        region: 'South',
        collegeInitial: 'VCU',
      },
      {
        name: 'Naz Mitrou-Long',
        college: 'Iowa State',
        position: 'PG',
        conference: 'Big 12',
        mascot: 'Cyclones',
        colors: ['Cardinal', 'Gold'],
        region: 'Midwest',
        collegeInitial: 'ISU',
      },
      {
        name: 'Chris Clemons',
        college: 'Campbell',
        position: 'PG',
        conference: 'Big South',
        mascot: 'Fighting Camels',
        colors: ['Orange', 'Black'],
        region: 'South',
        collegeInitial: 'CU',
      },
      {
        name: "E'Twaun Moore",
        college: 'Purdue',
        position: 'SG',
        conference: 'Big Ten',
        mascot: 'Boilermakers',
        colors: ['Black', 'Gold'],
        region: 'Midwest',
        collegeInitial: 'PU',
      },
      {
        name: 'James Ennis',
        college: 'Long Beach State',
        position: 'SF',
        conference: 'Big West',
        mascot: 'Beach',
        colors: ['Black', 'Gold'],
        region: 'West',
        collegeInitial: 'LBSU',
      },
      {
        name: 'Fred VanVleet',
        college: 'Wichita State',
        position: 'PG',
        conference: 'AAC',
        mascot: 'Shockers',
        colors: ['Black', 'Yellow'],
        region: 'Midwest',
        collegeInitial: 'WSU',
      },
      {
        name: 'Kyle Korver',
        college: 'Creighton',
        position: 'SG',
        conference: 'Big East',
        mascot: 'Bluejays',
        colors: ['Blue', 'White'],
        region: 'Midwest',
        collegeInitial: 'CU',
      },
      {
        name: 'Doug McDermott',
        college: 'Creighton',
        position: 'SF',
        conference: 'Big East',
        mascot: 'Bluejays',
        colors: ['Blue', 'White'],
        region: 'Midwest',
        collegeInitial: 'CU',
      },
      {
        name: 'Tacko Fall',
        college: 'UCF',
        position: 'C',
        conference: 'AAC',
        mascot: 'Knights',
        colors: ['Black', 'Gold'],
        region: 'South',
        collegeInitial: 'UCF',
      },
      {
        name: 'Duncan Robinson',
        college: 'Michigan',
        position: 'SG',
        conference: 'Big Ten',
        mascot: 'Wolverines',
        colors: ['Maize', 'Blue'],
        region: 'Midwest',
        collegeInitial: 'UM',
      },
      {
        name: 'Tyler Herro',
        college: 'Kentucky',
        position: 'SG',
        conference: 'SEC',
        mascot: 'Wildcats',
        colors: ['Blue', 'White'],
        region: 'South',
        collegeInitial: 'UK',
      },
      {
        name: 'Bones Hyland',
        college: 'VCU',
        position: 'PG',
        conference: 'Atlantic 10',
        mascot: 'Rams',
        colors: ['Black', 'Gold'],
        region: 'South',
        collegeInitial: 'VCU',
      },
      {
        name: 'Gary Trent Jr.',
        college: 'Duke',
        position: 'SG',
        conference: 'ACC',
        mascot: 'Blue Devils',
        colors: ['Royal Blue', 'White'],
        region: 'South',
        collegeInitial: 'DU',
      },
      {
        name: 'Tyrese Maxey',
        college: 'Kentucky',
        position: 'PG',
        conference: 'SEC',
        mascot: 'Wildcats',
        colors: ['Blue', 'White'],
        region: 'South',
        collegeInitial: 'UK',
      },
      {
        name: 'Monte Morris',
        college: 'Iowa State',
        position: 'PG',
        conference: 'Big 12',
        mascot: 'Cyclones',
        colors: ['Cardinal', 'Gold'],
        region: 'Midwest',
        collegeInitial: 'ISU',
      },
      {
        name: 'Max Strus',
        college: 'DePaul',
        position: 'SG',
        conference: 'Big East',
        mascot: 'Blue Demons',
        colors: ['Blue', 'Red'],
        region: 'Midwest',
        collegeInitial: 'DPU',
      },
      {
        name: 'Jose Alvarado',
        college: 'Georgia Tech',
        position: 'PG',
        conference: 'ACC',
        mascot: 'Yellow Jackets',
        colors: ['Old Gold', 'White'],
        region: 'South',
        collegeInitial: 'GT',
      },
      {
        name: 'Desmond Bane',
        college: 'TCU',
        position: 'SG',
        conference: 'Big 12',
        mascot: 'Horned Frogs',
        colors: ['Purple', 'White'],
        region: 'South',
        collegeInitial: 'TCU',
      },
      {
        name: 'Jae Crowder',
        college: 'Marquette',
        position: 'SF',
        conference: 'Big East',
        mascot: 'Golden Eagles',
        colors: ['Blue', 'Gold'],
        region: 'Midwest',
        collegeInitial: 'MU',
      },
      {
        name: 'Kendrick Nunn',
        college: 'Oakland',
        position: 'PG',
        conference: 'Horizon League',
        mascot: 'Golden Grizzlies',
        colors: ['Black', 'Gold'],
        region: 'Midwest',
        collegeInitial: 'OU',
      },
      {
        name: 'Patrick Beverley',
        college: 'Arkansas',
        position: 'PG',
        conference: 'SEC',
        mascot: 'Razorbacks',
        colors: ['Cardinal', 'White'],
        region: 'South',
        collegeInitial: 'UA',
      },
      {
        name: 'Jared Dudley',
        college: 'Boston College',
        position: 'SF',
        conference: 'ACC',
        mascot: 'Eagles',
        colors: ['Maroon', 'Gold'],
        region: 'Northeast',
        collegeInitial: 'BC',
      },
      {
        name: 'DeAndre Jordan',
        college: 'Texas A&M',
        position: 'C',
        conference: 'Big 12',
        mascot: 'Aggies',
        colors: ['Maroon', 'White'],
        region: 'South',
        collegeInitial: 'TAMU',
      },
      {
        name: "Royce O'Neale",
        college: 'Baylor',
        position: 'SF',
        conference: 'Big 12',
        mascot: 'Bears',
        colors: ['Green', 'Gold'],
        region: 'South',
        collegeInitial: 'BU',
      },
      {
        name: 'Davion Mitchell',
        college: 'Baylor',
        position: 'PG',
        conference: 'Big 12',
        mascot: 'Bears',
        colors: ['Green', 'Gold'],
        region: 'South',
        collegeInitial: 'BU',
      },
      {
        name: 'Grant Williams',
        college: 'Tennessee',
        position: 'PF',
        conference: 'SEC',
        mascot: 'Volunteers',
        colors: ['Orange', 'White'],
        region: 'South',
        collegeInitial: 'UT',
      },
      {
        name: 'Derrick White',
        college: 'Colorado',
        position: 'PG',
        conference: 'Pac-12',
        mascot: 'Buffaloes',
        colors: ['Black', 'Gold'],
        region: 'West',
        collegeInitial: 'CU',
      },
      {
        name: 'Cam Payne',
        college: 'Murray State',
        position: 'PG',
        conference: 'Missouri Valley',
        mascot: 'Racers',
        colors: ['Navy', 'Gold'],
        region: 'South',
        collegeInitial: 'MUR',
      },
      {
        name: 'Jared Cunningham',
        college: 'Oregon State',
        position: 'SG',
        conference: 'Pac-12',
        mascot: 'Beavers',
        colors: ['Orange', 'Black'],
        region: 'West',
        collegeInitial: 'OSU',
      },
      {
        name: 'Alondes Williams',
        college: 'Wake Forest',
        position: 'SG',
        conference: 'ACC',
        mascot: 'Demon Deacons',
        colors: ['Old Gold', 'Black'],
        region: 'South',
        collegeInitial: 'WFU',
      },
];

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
    await dbConnect();

    try {
        await Player.insertMany(obscurePlayers);
        res.status(201).json({ message: 'Players seeded successfully!' });
    } catch (error) {
        res.status(500).json({ message: 'Error seeding players', error });
    }
}